<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Page;
use App\Services\AuditService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\View\View;

/**
 * Generic CMS page editor. content_blocks is a page-specific, arbitrarily
 * nested associative array — rather than a bespoke form per page (or the
 * raw-JSON textarea this replaced), the edit form is generated by
 * recursively walking that array (see admin.pages.partials.field) and
 * typing each leaf/list by its shape: scalar → text/textarea, list of
 * scalars → one-per-line textarea, list of associative arrays → a
 * repeater of cards. reconstructValue() below performs the inverse
 * conversion from submitted form data back into that same shape and MUST
 * stay in sync with the type rules in the partial.
 */
class PageController extends Controller
{
    public function index(): View
    {
        return view('admin.pages.index', ['pages' => Page::orderBy('slug')->get()]);
    }

    public function edit(string $slug): View
    {
        $page = Page::where('slug', $slug)->firstOrFail();

        return view('admin.pages.edit', ['page' => $page]);
    }

    public function update(Request $request, string $slug, AuditService $audit): RedirectResponse
    {
        $page = Page::where('slug', $slug)->firstOrFail();

        $data = $request->validate([
            'title' => ['required', 'string', 'max:150'],
            'blocks' => ['nullable', 'array'],
        ]);

        $before = $page->content_blocks;
        $blocks = $this->reconstructValue($before, $data['blocks'] ?? []);
        $page->update(['title' => $data['title'], 'content_blocks' => $blocks]);
        Cache::forget("page:{$slug}");

        $audit->record($request->user(), 'page.update', $page, ['before' => $before, 'after' => $blocks]);

        return redirect()->route('admin.pages.edit', $slug)->with('status', 'Page content updated.');
    }

    /**
     * Rebuilds a content_blocks value from submitted form data, using the
     * existing $original value at the same path purely as a shape template
     * (never as a fallback value) — this is what lets an untyped HTML form
     * round-trip an arbitrarily nested array without per-page field lists.
     */
    private function reconstructValue(mixed $original, mixed $submitted): mixed
    {
        if (is_bool($original)) {
            return $submitted === '1' || $submitted === true;
        }

        if (! is_array($original)) {
            return is_string($submitted) ? trim($submitted) : $submitted;
        }

        if ($original === [] || ! array_is_list($original)) {
            $result = [];
            foreach ($original as $key => $origVal) {
                $result[$key] = $this->reconstructValue($origVal, is_array($submitted) ? ($submitted[$key] ?? null) : null);
            }

            return $result;
        }

        $isListOfAssoc = collect($original)->every(fn ($v) => is_array($v));

        if (! $isListOfAssoc) {
            // List of scalars — submitted is the raw textarea text, one item per line.
            $text = is_string($submitted) ? $submitted : '';

            return array_values(array_filter(array_map('trim', preg_split('/\r?\n/', $text)), fn ($line) => $line !== ''));
        }

        // List of associative rows (a "repeater"). The union of keys across
        // every existing row is the shape template for any row beyond the
        // original count (i.e. a blank spare card the admin filled in).
        $unionTemplate = [];
        foreach ($original as $row) {
            $unionTemplate += $row;
        }

        $rows = [];
        foreach (array_values(is_array($submitted) ? $submitted : []) as $i => $rowSubmitted) {
            $schema = $original[$i] ?? $unionTemplate;
            $row = $this->reconstructValue($schema, $rowSubmitted);

            if (! $this->isBlankRow($row)) {
                $rows[] = $row;
            }
        }

        return $rows;
    }

    private function isBlankRow(mixed $value): bool
    {
        if (is_array($value)) {
            foreach ($value as $v) {
                if (! $this->isBlankRow($v)) {
                    return false;
                }
            }

            return true;
        }

        if (is_bool($value)) {
            return $value === false;
        }

        return trim((string) $value) === '';
    }
}
